#!/usr/bin/env bash
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    echo "Error: this script should be sourced, not executed"
    exit 1
fi

DIR="$(builtin cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ACTIVATE="$DIR/lib/install/bin/activate"

if [ ! -f "$ACTIVATE" ]; then
    echo -n "Error: virtualenv not installed correctly, run bootstrap.sh to "
    echo    "install dependencies first"
    return 1
fi

echo "Switching to virtualenv, run 'deactivate' to switch back out"
source "$ACTIVATE"
